flags: {}
extra-package-dbs: []
packages:
- hip
- hip-chart
resolver: lts-16.22
extra-deps: #for now, since we might need to add changes to upstream deps
- scheduler-1.5.0
#- massiv-0.5.5.0
- github: lehins/massiv
  commit: 0a15ce17bcfdb88d76cd90ce06896f9a8c99b55c
  subdirs:
    - massiv
#- massiv-io-0.4.0.0
- github: lehins/massiv-io
  commit: 8f6b916b9daea8c6b8e97a3e923e21e07444fd42
  subdirs:
    - massiv-io
- github: lehins/Color
  commit: c970293f549b132ccb2558eb06abc72061088330
  subdirs:
    - Color

