flags: {}
extra-package-dbs: []
packages:
- hip
- hip-chart
resolver: lts-16.0
extra-deps: #for now, since we might need to add changes to upstream deps
- github: lehins/massiv
  commit: 663471b65d465bd020116abc3ac15c7e20e5042d
  subdirs:
    - massiv
- github: lehins/massiv-io
  commit: 6bd00a6798689018243559d53da00a0e464fa0ff
  subdirs:
    - massiv-io
- github: lehins/Color
  commit: 669ff826c60e28fe7e4646f28a73eba9bb9d3d13
  subdirs:
    - Color

