flags: {}
extra-package-dbs: []
packages:
- '.'
resolver: lts-16.0
extra-deps: #for now, since we might need to add changes to upstream deps
- github: lehins/massiv
  commit: 4fdc959542193f95b9a5da7f44b7cc90868b68be
  subdirs:
    - massiv
- github: lehins/massiv-io
  commit: 3501c8930179345a634e1ad66ea7f746ba599986
  subdirs:
    - massiv-io
- github: lehins/Color
  commit: c566a3083a238eba70e61ba0e261f9dacb8481bb
  subdirs:
    - Color

